### ISSUE TITLE
运行时间长容易卡住

### ISSUE THREAD

**Issue by terrydash** [muzexi3000/swarmdog#1]
估计有内存泄露问题。。
运行了一会就失去响应了。。。

**Comment by muzexi3000** [comment]
是的，已经在1.1版本中就行了修复，有问题欢迎再反馈

**Comment by muzexi3000** [comment]
> 估计有内存泄露问题。。
> 运行了一会就失去响应了。。。

是的，已经在1.1版本中进行了修复，有问题欢迎再反馈
